### ISSUE TITLE
[Feature Request]: Add WinGet Releaser

### ISSUE THREAD

**Issue by russellbanks** [FreeTubeApp/FreeTube#2459]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

Packages are currently submitted to winget manually, by me and other winget-pkgs contributors.

### Proposed Solution

Add [WinGet Releaser](https://github.com/vedantmgoyal2009/winget-releaser), a GitHub actions workflow for automatically submitting updated manifests to [winget-pkgs](https://github.com/microsoft/winget-pkgs).

It would look like this:
```yaml
name: Publish to WinGet
on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@latest
        with:
          identifier: PrestonN.FreeTube
          installers-regex: '\.exe$'
          token: ${{ secrets.WINGET_TOKEN }}
```

I'm happy to make a pull request for this, but I wasn't sure where would be best to integrate this into the existing release workflows.

### Alternatives Considered

N/A

### Issue Labels

new feature

### Additional Information

Pull requests are triggered on release, and done through a personal access token, as shown below (with a different user, of course).

![firefox_p6iB2rculY](https://user-images.githubusercontent.com/74878137/183256316-a6b35548-2eb1-40a2-9d18-a199ec87cf7b.png)
