### ISSUE TITLE
Use a Flexbox to display the grid

### ISSUE THREAD

**Issue by cjfloss** [FreeTubeApp/FreeTube#296]
In the div that wraps around all the videos on the grid you could use the new CSS Flexboxlike this

```css
{
    display: flex;
    flex-wrap: wrap;
    justify-content: space-evenly;
}
```

This would make the videos use all the space on the screen and not have they all aligned left with empty space on the right.
