### ISSUE TITLE
[Feature Request]: Larger search/URL bar

### ISSUE THREAD

**Issue by 4yman-0** [FreeTubeApp/FreeTube#5341]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Space waste

### Proposed Solution

Make search/URL bar (top of window) larger when there is enough space.

### Alternatives Considered

only extend search bar when "Hide FreeTube Header Logo" is enabled

### Issue Labels

visual improvement

### Additional Information

There will be a lot of discussion ;)

**Comment by 4yman-el** [comment]
Here's how it looks like in 2k using DevTools Device toolbar.
A max of 440px is not good for all devices, At least there will be some information (URL/search for example) rather than an empty background. We can also add spacing to make it look nice.
![demo](https://github.com/FreeTubeApp/FreeTube/assets/170770027/aa627d02-8fbf-4023-8067-9175616a80f7)

**Comment by kommunarr** [comment]
I'm not opposed to increasing the max size & better responsive design. For reference, Gmail Web maxes out at 720px but shrinks if the viewport width doesn't suffice.

**Comment by 4yman-el** [comment]
This is the window where increased the max to 720px and made grid `repeat(3, 1fr)`
![Demo of large search bar](https://github.com/FreeTubeApp/FreeTube/assets/170770027/1e04c30f-b675-4c4c-a556-b60ddf9ca7a2)

Here is the CSS:

```css
@media only screen and (width >= 961px) {
    .topNav[data-v-284c500a] {
        display: grid;
        grid-template-columns: repeat(3, 1fr);
    }
}
```

```css
.middle[data-v-284c500a] {
    flex: 1;
    max-inline-size: 720px;
}
```
